### ISSUE TITLE
Setup & building is not working

### ISSUE THREAD

**Issue by ahelmel** [Talento90/typescript-node#3]
Hi, 
i cloned the project, executed "npm run setup":

```
> typescript-node@1.0.0 setup /Users/arthur/Development/arthel/nodejs/cheerio/lazygold/backend/lazygold-price_typescript
> npm install & typings install
└── (No dependencies)
```

Then i executed "npm run build":

```
> typescript-node@1.0.0 build /Users/arthur/Development/arthel/nodejs/cheerio/lazygold/backend/lazygold-price_typescript
> gulp build

[16:47:28] Using gulpfile ~/Development/arthel/nodejs/cheerio/lazygold/backend/lazygold-price_typescript/gulpfile.js
[16:47:28] Starting 'tslint'...
[16:47:28] Starting 'compile'...
TypeScript  Version 1.8.10

[16:47:29] Finished 'tslint' after 1.31 s
src/controllers/taskController.ts(1,23): error TS2307: Cannot find module 'hapi'.
src/controllers/taskController.ts(2,23): error TS2307: Cannot find module 'boom'.
src/controllers/taskController.ts(3,22): error TS2307: Cannot find module 'joi'.
src/libs/ioc/index.ts(4,13): error TS2304: Cannot find name 'process'.
src/libs/ioc/index.ts(8,1): error TS2304: Cannot find name 'require'.
src/libs/plugins/interfaces.ts(1,23): error TS2307: Cannot find module 'hapi'.
src/libs/repository/mongo/mongoRepository.ts(1,26): error TS2307: Cannot find module 'mongodb'.
src/models/taskModel.ts(1,22): error TS2307: Cannot find module 'joi'.
src/routes/index.ts(1,23): error TS2307: Cannot find module 'hapi'.
src/server.ts(2,23): error TS2307: Cannot find module 'hapi'.
src/server.ts(5,23): error TS2307: Cannot find module 'path'.
src/server.ts(6,21): error TS2307: Cannot find module 'fs'.
src/server.ts(11,14): error TS2304: Cannot find name 'process'.
src/server.ts(22,21): error TS2304: Cannot find name '__dirname'.
src/server.ts(26,28): error TS2304: Cannot find name 'require'.
typings.d.ts(1,1): error TS6053: File '/Users/arthur/Development/arthel/nodejs/cheerio/lazygold/backend/lazygold-price_typescript/typings/main.d.ts' not found.
src/configs/configurations.ts(10,21): error TS2304: Cannot find name 'process'.
src/configs/configurations.ts(11,24): error TS2304: Cannot find name 'require'.
src/index.ts(3,35): error TS2304: Cannot find name 'process'.
src/libs/ioc/inversify.dev.config.ts(1,10): error TS2305: Module '"inversify"' has no exported member 'IKernel'.
src/libs/ioc/inversify.test.config.ts(1,10): error TS2305: Module '"inversify"' has no exported member 'IKernel'.
src/libs/plugins/logger/index.ts(2,23): error TS2307: Cannot find module 'hapi'.
src/libs/plugins/logger/index.ts(10,31): error TS2304: Cannot find name 'require'.
src/libs/plugins/logger/index.ts(16,27): error TS2304: Cannot find name 'require'.
src/libs/plugins/swagger/index.ts(2,23): error TS2307: Cannot find module 'hapi'.
src/libs/plugins/swagger/index.ts(8,17): error TS2304: Cannot find name 'require'.
src/libs/plugins/swagger/index.ts(9,17): error TS2304: Cannot find name 'require'.
src/libs/plugins/swagger/index.ts(11,31): error TS2304: Cannot find name 'require'.
test/repository/memory/taskRepositoryTests.ts(2,23): error TS2307: Cannot find module 'chai'.
test/repository/memory/taskRepositoryTests.ts(9,1): error TS2304: Cannot find name 'describe'.
test/repository/memory/taskRepositoryTests.ts(10,3): error TS2304: Cannot find name 'it'.
test/repository/mongo/taskRepositoryTests.ts(2,23): error TS2307: Cannot find module 'chai'.
test/repository/mongo/taskRepositoryTests.ts(13,1): error TS2304: Cannot find name 'describe'.
test/repository/mongo/taskRepositoryTests.ts(14,3): error TS2304: Cannot find name 'it'.
test/server/taskControllerTests.ts(2,23): error TS2307: Cannot find module 'chai'.
test/server/taskControllerTests.ts(10,1): error TS2304: Cannot find name 'describe'.
test/server/taskControllerTests.ts(11,5): error TS2304: Cannot find name 'it'.
test/server/taskControllerTests.ts(18,5): error TS2304: Cannot find name 'it'.
test/server/taskControllerTests.ts(36,5): error TS2304: Cannot find name 'it'.
test/server/taskControllerTests.ts(43,5): error TS2304: Cannot find name 'it'.

[16:47:31] 'compile' errored after 2.82 s
[16:47:31] Error: Command failed: tsc

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)

npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/arthur/.nvm/versions/node/v5.10.1/bin/node" "/Users/arthur/.nvm/versions/node/v5.10.1/bin/npm" "run" "build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! typescript-node@1.0.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript-node@1.0.0 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the typescript-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs typescript-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls typescript-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/arthur/Development/arthel/nodejs/cheerio/lazygold/backend/lazygold-price_typescript/npm-debug.log

```

**Comment by Talento90** [comment]
Thanks for reporting the issue! :+1: 

I'm going to fix it as soon I can :)

**Comment by Talento90** [comment]
@ahelmel I have fixed all issues!

Have fun :+1:
